# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - "**"
    

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre linting
      run: npm install    
    - name: Linting Starts 
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre testing
      run: npm install
    - name: Unit Testing Starts
      run: npm run test

  s3deploy:
    if: github.ref == 'refs/heads/master' 
    name: Build and deploy static html on s3 bucket
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Build react app
      run: |
        npm install
        npm run build
    - name: Uploading to s3  
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: 'build'
    - name: invalidate cloudfront distribution
      uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
      env:
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        PATHS: '/*'
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  build:
    if: github.ref == 'refs/heads/master' 
    name: Build static html files
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Build react app
        run: |
          npm install
          npm run build
      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host : ${{secrets.REMOTE_HOST}}
          username : ${{secrets.REMOTE_USER}}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "build/*"
          target: "${{ secrets.REMOTE_DIR }}"
  
  webhookDeploy:
    if: github.ref == 'refs/heads/master'
    name: Trigger webhook on AWS instance 
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Deploy the copied html files
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
