# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - "**"
    

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre linting
      run: npm install    
    - name: Linting Starts 
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre testing
      run: npm install
    - name: Unit Testing Starts
      run: npm run test

  build:
    if: github.ref == 'refs/heads/master' 
    name: Build static html files
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Build react app
        run: |
          npm install
          npm run build
      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host : ${{secrets.REMOTE_HOST}}
          username : ${{secrets.REMOTE_USER}}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "build/*"
          target: "${{ secrets.REMOTE_DIR }}"
  
  webhookDeploy:
    if: github.ref == 'refs/heads/master'
    name: Trigger webhook on AWS instance 
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Deploy the copied html files
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
